Description: "This cloudformation template creates AWS VPC, an Amazon Redshift Instance and Matillion software installed in a single EC2 machine."
Metadata:
  LICENSE: EULA - Matillion ETL for Redshift
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: End User License Agreement (EULA) - Matillion ETL for Redshift
      Parameters:
      - AcceptedEULA
    - Label:
        default: VPC network configuration
      Parameters:
      - AvailabilityZones
      - VPCCIDR
      - PrivateSubnet1CIDR
      - PrivateSubnet2CIDR
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - RemoteAccessCIDR
    - Label:
        default: Matillion EC2 instance configuration 
      Parameters:
      - MatillionEC2InstanceType
      - KeyPairName
    - Label:
        default: Matillion Aurora/PostgreSQL repository configuration 
      Parameters:
      - PGInstanceClass
      - PGDBName
      - PGMasterUsername
      - PGMasterUserPassword
      - PGDBPort
      - NotificationList
    - Label:
        default: Amazon Redshift configuration 
      Parameters:
      - EnableRedshiftStack
      - RedshiftDBName
      - RedshiftDBPort
      - RedshiftNodeType
      - RedshiftNumberOfNodes
      - RedshiftMasterUsername
      - RedshiftMasterUserPassword
      - RedshiftEnableLoggingToS3
      - RedshiftMaxConcurrentCluster
      - RedshiftEncryptionAtRest
      - Redshiftkmskey
      - RedshiftS3BucketForIAMRole
      - RedshiftMaintenancewindow
      - RedshiftSnapshotIdentifier
      - RedshiftSnapshotAccountNumber
    - Label:
        default: Tag identifiers
      Parameters:
      - TagEnvironment
      - TagName
    - Label:
        default: AWS Quick Start configuration 
      Parameters:
      - QSS3BucketName
      - QSS3KeyPrefix
    ParameterLabels:
      AcceptedEULA:
        default: Accepted EULA from AWS Marketplace
      AvailabilityZones:
        default: Availability Zones
      VPCCIDR:
        default: VPC CIDR
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      RemoteAccessCIDR:
        default: Allowed external access CIDR
      MatillionEC2InstanceType:
        default: Matillion EC2 instance type
      KeyPairName:
        default: Key pair name
      PGInstanceClass:
        default: Aurora/PostgreSQL instance class 
      PGDBName:
        default: Aurora/PostgreSQL database name
      PGDBPort:
        default: Aurora/PostgreSQL database port
      PGMasterUsername:
        default: Aurora/PostgreSQL master username
      PGMasterUserPassword:
        default: Aurora/PostgreSQL master password
      NotificationList:
        default: SNS notification email
      EnableRedshiftStack:
        default: Do you want to create Redshift cluster stack? 
      RedshiftDBName:
        default: Redshift database name
      RedshiftDBPort:
        default: Redshift cluster port
      RedshiftNodeType:
        default: Node type for Redshift cluster
      RedshiftNumberOfNodes:
        default: Number of nodes in Redshift cluster
      RedshiftMasterUsername:
        default: Redshift master user name
      RedshiftMasterUserPassword:
        default: Redshift master user password
      RedshiftEnableLoggingToS3:
        default: Enable Redshift logging to S3
      RedshiftMaxConcurrentCluster:
        default: Max. number of concurrent clusters
      RedshiftEncryptionAtRest:
        default: Encryption at rest
      Redshiftkmskey:
        default: KMS key ID
      RedshiftS3BucketForIAMRole:
        default: Amazon S3 bucket for Redshift IAM role
      RedshiftMaintenancewindow:
        default: Maintenance window
      RedshiftSnapshotIdentifier:
        default: Redshift snapshot identifier
      RedshiftSnapshotAccountNumber:
        default: AWS account-ID of the Redshift Snapshot
      TagEnvironment:
        default: Environment
      TagName:
        default: Unique friendly name
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
    
  AcceptedEULA: 
    AllowedValues: 
      - "Yes"
    Default: "Yes"
    Description: >- 
        PLEASE READ THE MATILLION ETL FOR REDSHIFT EULA (https://redshift-support.matillion.com/s/article/2845300) CAREFULLY BEFORE USING THE SOFTWARE. 
        The Matillion stack can be created only if you have already accepted the EULA. To accept the EULA, see https://aws.amazon.com/marketplace/pp/B010ED5YF8.     
    Type: String
    
  AvailabilityZones:
   Description: >-
      List of Availability Zones to use for the subnets in the VPC. Only two
      Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
   Type: 'List<AWS::EC2::AvailabilityZone::Name>'
    
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
    
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
    
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 2 located in Availability Zone 2.
    Type: String
    
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR block for the public subnet 1 located in Availability Zone 1.
    Type: String
    
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR block for the public subnet 2 located in Availability Zone 2.
    Type: String
    
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block in the format x.x.x.x/x for external SSH access to the Matillion Stack.
    Type: String
    
  MatillionEC2InstanceType:
    AllowedValues:
    - m5.large
    - m5.xlarge
    - m3.medium
    - t2.medium
    - t3.medium
    - m3.large
    - m4.large
    - m5.large
    - r3.large
    - r4.large
    - m3.xlarge
    - m4.xlarge
    - m5.xlarge
    - r3.xlarge
    - r4.xlarge
    - t3.xlarge
    - x1e.xlarge
    - m5.2xlarge
    - r3.2xlarge
    Default: m4.large
    Description: "The Amazon EC2 instance type for the Matillion instance. A larger instance type enables greater workload concurrency. For more information, see https://www.matillion.com/pricing/etl-for-redshift/."
    Type: String
      
  KeyPairName:
    Description: A public/private key pair, which allows you to connect securely to your instance after it launches. This is the key pair you created in your preferred AWS Region; see the Technical requirements section. If you do not have one in this AWS Region, create it before continuing.
    Type: 'AWS::EC2::KeyPair::KeyName'
    
  PGInstanceClass:
    AllowedValues:
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    Default: db.r5.large
    Description: The Aurora/PostgreSQL database instance class.
    Type: String
    
  PGDBName:
    AllowedPattern: "([a-z]|[0-9])+"
    Default: matillion
    Description: The Aurora/PostgreSQLs database name for the Matillion repository.
    Type: String
    
  PGDBPort:
    Default: 8201
    Description: The port number on which the Aurora/PostgreSQL database accepts incoming connections. 
    MaxValue: 65535
    MinValue: 1150
    Type: Number
    
  PGMasterUsername:
    AllowedPattern: "^[a-zA-Z]{1}[a-z0-9]*"
    Default: matillion
    Description: The user name that is associated with the master user account for the Aurora DB that is being created.
    Type: String
    
  PGMasterUserPassword:
    AllowedPattern: '(?=^.{6,255}$)((?=.*\\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*'
    Description: The Aurora/PostgreSQL master user password. Min 8 chars, must include 1 uppercase, 1 lowercase, 1 number, 1 (non / @ " ') symbol.
    NoEcho: true
    Type: String
    
  NotificationList:
    Type: String
    Description: The email notification list that is used to configure an SNS topic for sending Amazon CloudWatch alarm and event notifications.
    Default: "ops@company.com"
    AllowedPattern: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
    ConstraintDescription: Provide a valid email address.
    
  EnableRedshiftStack: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: Enables or disables creation of an Amazon Redshift stack. If true, an Amazon Redshift stack will be created.
    Type: String
    
  RedshiftDBName:
    Description: The name of the first database to be created in the cluster is created.
    Type: String
    Default: matillion
    AllowedPattern: "([a-z]|[0-9])+"
    ConstraintDescription: must contain a-z or 0-9 only.
    
  RedshiftDBPort:
    Description: The port number on which the cluster accepts incoming connections.
    Type: String
    Default: '8200'
    
  RedshiftNodeType:
    Description: The type of node to be provisioned
    Type: String
    Default: dc2.large
    AllowedValues:
      - dc2.large
      - dc2.8xlarge
      - ds2.xlarge
      - ds2.8xlarge
    ConstraintDescription: must be a valid Amazon Redshift node type.
    
  RedshiftNumberOfNodes:
    Description: The number of compute nodes in the Amazon Redshift cluster.
    Type: Number
    Default: '2'
    
  RedshiftMasterUsername:
    Description: The user name that is associated with the master user account for the cluster that is being created.
    Type: String
    Default: matillion
    AllowedPattern: '([a-z])([a-z]|[0-9])*'
    ConstraintDescription: must start with a-z and contain only a-z or 0-9.
    
  RedshiftMasterUserPassword:
    Description: >-
        The password that is associated with the master user account for the cluster that is being created. Must have at least 8 characters and no more than 64 characters, 
        and must include 1 uppercase letter, 1 lowercase letter, 1 number, and 1 symbol (excluding / @ \" ').
    NoEcho: true
    Type: String
    MinLength: '8'
    MaxLength: '64'
    AllowedPattern: '(?=^.{6,255}$)((?=.*\\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*'
    ConstraintDescription: >-
       Enter alphanumeric password for the master user. The password must contain 8 to 64 printable ASCII characters, excluding: /, ", \'', \ and @. It must contain one uppercase letter, one lowercase letter, and one number.
    
  RedshiftEnableLoggingToS3:
    Default: 'false'
    Type: String
    AllowedValues:
      - true
      - false
    Description: Enables or disables logging to an S3 bucket.  To enable logging, select true.
        
  RedshiftMaxConcurrentCluster:
    Description: The maximum number of concurrency scaling Redshift clusters.
    Type: String
    Default: '1'
    
  RedshiftEncryptionAtRest:
    Description: Enables or disables encryption at rest of the Redshift database.
    Type: String
    Default: 'false'
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be true or false.
  
  Redshiftkmskey:
    Description: The existing KMS key ID for encrypting Redshift database at-rest.
    Type: String
    Default: ''
    
  RedshiftS3BucketForIAMRole:
    Type: String
    Description: The existing Amazon S3 bucket. An IAM role will be created and associated to the Redshift cluster with GET and LIST access to this bucket.
    Default: ''

  RedshiftMaintenancewindow:
    Description: The maintenance window for the Amazon Redshift cluster.
    Type: String
    Default: 'sat:05:00-sat:05:30'
    
  RedshiftSnapshotIdentifier:
    Description: The Redshift snapshot identifier. Leave this blank for a new cluster. Enter the snapshot identifier, only if you want to restore from a snapshot.
    Type: String
    Default: ''
    
  RedshiftSnapshotAccountNumber:
    Description: The AWS account number where the Amazon Redshift snapshot was created. Leave this blank, if the snapshot was created in the current AWS account.
    Type: String
    Default: ''
    
  TagName:
    Type: String
    Description: 'The unique friendly name as required by your company’s tagging strategy document, and will be added to the tag.'
    Default: 'matillion-qs'
    
  TagEnvironment:
    Type: String
    AllowedValues:
      - dev
      - test
      - pre-prod
      - prod
      - none
    Default: 'dev'
    Description: 'Designates the environment stage of the associated AWS resource.'
    
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: 'aws-quickstart'
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: String
    
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: 'quickstart-matillion-etl/'
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: String
    
Conditions:
  GovCloudCondition: !Equals 
    - !Ref 'AWS::Region'
    - us-gov-west-1
  CreateRedshiftStack: !Equals
    - !Ref EnableRedshiftStack
    - "true"
  IsAcceptedEULA: !Equals # This condition does not look like it was enforced properly so it could be removed (i.e. it's possible to launch the stack with this disabled)
    - !Ref AcceptedEULA
    - "Yes"

Resources:

  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
        - QSS3Region:
            Fn::If:
            - GovCloudCondition
            - s3-us-gov-west-1
            - s3
      Parameters:
        AvailabilityZones: !Join 
          - ','
          - !Ref AvailabilityZones
        KeyPairName: !Ref KeyPairName
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        VPCCIDR: !Ref VPCCIDR
        
  MatillionStack:
    Condition: IsAcceptedEULA
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}templates/matillion_single_aurora.yaml
        - QSS3Region: !If [GovCloudCondition , s3-us-gov-west-1 , s3]
      Parameters:
        AcceptedEULA: !Ref AcceptedEULA
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
        PublicSubnet1: !GetAtt 
          - VPCStack
          - Outputs.PublicSubnet1ID
        PrivateSubnet1:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1AID
        PrivateSubnet2:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2AID
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        MatillionEC2InstanceType: !Ref MatillionEC2InstanceType
        KeyPairName: !Ref KeyPairName
        PGMasterUsername: !Ref PGMasterUsername
        PGMasterUserPassword: !Ref PGMasterUserPassword
        PGDBPort: !Ref PGDBPort
        PGDBName: !Ref PGDBName
        PGInstanceClass: !Ref PGInstanceClass
        NotificationList: !Ref NotificationList
        TagEnvironment: !Ref TagEnvironment
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        
  RedshiftStack:
    Condition: CreateRedshiftStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 
        - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-amazon-redshift/templates/redshift.template.yaml
        - QSS3Region: !If [GovCloudCondition , s3-us-gov-west-1 , s3]
      Parameters:
        Subnet1ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1AID
        Subnet2ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2AID
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
        RemoteAccessCIDR: !Ref VPCCIDR
        PubliclyAccessible: 'false'
        DatabaseName: !Ref RedshiftDBName
        RedshiftClusterPort: !Ref RedshiftDBPort
        NumberOfNodes: !Ref RedshiftNumberOfNodes
        NodeType: !Ref RedshiftNodeType
        MasterUsername: !Ref RedshiftMasterUsername
        MasterUserPassword: !Ref RedshiftMasterUserPassword
        Maintenancewindow: !Ref RedshiftMaintenancewindow
        MaxConcurrentCluster: !Ref RedshiftMaxConcurrentCluster
        EncryptionAtRest: !Ref RedshiftEncryptionAtRest
        kmskey: !Ref Redshiftkmskey
        SnapshotIdentifier: !Ref RedshiftSnapshotIdentifier
        SnapshotAccountNumber: !Ref RedshiftSnapshotAccountNumber
        NotificationList: !Ref NotificationList
        EnableLoggingToS3: !Ref RedshiftEnableLoggingToS3
        S3BucketForRedshiftIAMRole: !Ref RedshiftS3BucketForIAMRole
        GlueCatalogDatabase: ''
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        TagName: !Ref TagName
        TagEnvironment: !Ref TagEnvironment

Outputs:
  MatillionEc2InstancePublicEndpoint:
    Description: Public Endpoint for Matillion Instance
    Value:
      Fn::GetAtt:
      - MatillionStack
      - Outputs.MatillionEc2InstancePublicEndpoint
  RDSJDBCConnectionString:
    Description: JDBC connection string for Matillion RDS/Postgres DB
    Value:
      Fn::GetAtt:
      - MatillionStack
      - Outputs.RDSJDBCConnectionString
  RedshiftClusterEndpoint:
    Condition: CreateRedshiftStack
    Description: Redshift Cluster endpoint
    Value:
      Fn::GetAtt:
      - RedshiftStack
      - Outputs.RedshiftClusterEndpoint
