AWSTemplateFormatVersion: 2010-09-09
Description: RDS Postgres Database for use in Atlassian Standard Infrastructure (qs-)
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - Subnet1ID
      - Subnet2ID
      - CustomDBSecurityGroup
    - Label:
        default: Database configuration
      Parameters:
      - DBName
      - DBPort
      - DBEngineVersion
      - DBInstanceClass
      - DBMultiAZ
      - DBMasterUsername
      - DBMasterUserPassword
      - DBStorageType
      - DBAllocatedStorage
      - DBIops
      - DBAllocatedStorageEncrypted
      - DBAutoMinorVersionUpgrade
      - DBBackupRetentionPeriod
      - NotificationList
      - EnableEventSubscription
    ParameterLabels:
      DBName:
        default: Database name
      DBEngineVersion:
        default: Database Engine Version
      DBAllocatedStorageEncrypted:
        default: Database encryption enabled
      DBAutoMinorVersionUpgrade:
        default: Database auto minor version upgrade
      DBBackupRetentionPeriod:
        default: Database backup retention period
      DBInstanceClass:
        default: Database instance class
      DBMasterUsername:
        default: Database master username
      DBMasterUserPassword:
        default: Database master password
      DBPort:
        default: Database port
      DBMultiAZ:
        default: Multi-AZ deployment
      Subnet1ID:
        default: Private subnet 1 ID
      Subnet2ID:
        default: Private subne 2 ID
      CustomDBSecurityGroup:
        default: Custom securiy group ID
      EnableEventSubscription:
        default: Enable Event Subscription
      NotificationList:
        default: SNS notification email
Parameters:
  DBAutoMinorVersionUpgrade:
    Default: true
    AllowedValues:
      - true
      - false
    Description: "Select true/false to setup Auto Minor Version upgrade. e.g. PostgreSQL 9.6.8 -> 9.6.11"
    Type: String
  DBBackupRetentionPeriod: 
    Default: "7"
    Description: "The number of days for which automatic database snapshots are retained."
    Type: String
  DBInstanceClass:
    Default: db.m4.xlarge
    AllowedValues:
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.m4.large
      - db.m4.xlarge
      - db.m4.2xlarge
      - db.m4.4xlarge
      - db.m4.10xlarge
      - db.m4.16xlarge
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
      - db.t3.medium
      - db.t3.large
      - db.t3.xlarge
      - db.t3.2xlarge
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge
    ConstraintDescription: Must be a valid RDS instance class from the list
    Description: RDS instance type
    Type: String
  DBIops:
    Default: 1000
    ConstraintDescription: Must be in the range 1000 - 30000.
    Description: 'Must be in the range of 1000 - 30000 and a multiple of 1000. This value is only used with Provisioned IOPS. Note: The ratio of IOPS per allocated-storage must be between 3.00 and 10.00.'
    MinValue: 1000
    MaxValue: 30000
    Type: Number
  DBMasterUsername:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
    Default: postgres
    Description: The database admin account username
    MaxLength: '16'
    MinLength: '1'
    Type: String
  DBMasterUserPassword:
    AllowedPattern: '(?=^.{6,255}$)((?=.*\\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*'
    ConstraintDescription: "Min 8 chars. Must include 1 uppercase, 1 lowercase, 1 number, 1 (non / @ \" ') symbol"
    Description: Password for the master ('postgres') account.
    MinLength: 8
    MaxLength: 128
    NoEcho: true
    Type: String
  DBMultiAZ:
    Description: Whether to provision a multi-AZ RDS instance.
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be 'true' or 'false'.
    Type: String
  DBPort:
    Default: 8202
    Description: "The port the instance will listen for connections on."
    Type: Number
    ConstraintDescription: 'Must be in the range [1150-65535].'
    MinValue: 1150
    MaxValue: 65535
  DBName: 
    AllowedPattern: "[a-zA-Z0-9]*"
    Description: "Name of the RDS/Postgres database."
    MaxLength: "64"
    MinLength: "0"
    Default: 'devdb01'
    Type: String
  DBAllocatedStorage:
    Default: 10
    Description: Database allocated storage size, in gigabytes (GB). If you choose Provisioned IOPS, storage should be between 100 and 6144
    Type: Number
  DBAllocatedStorageEncrypted:
    Default: false
    AllowedValues:
      - true
      - false
    Description: Whether or not to encrypt the database
    Type: String
  DBStorageType:
    Default: General Purpose (SSD)
    AllowedValues:
      - General Purpose (SSD)
      - Provisioned IOPS
    ConstraintDescription: Must be 'General Purpose (SSD)' or 'Provisioned IOPS'.
    Description: Database storage type
    Type: String
  NotificationList:
    Type: String
    Default: 'db-ops@domain.com'
    Description: The email notification used to configure an SNS topic for sending CloudWatch alarm and RDS event notifications.
    AllowedPattern: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
    ConstraintDescription: Provide a valid email address.
  EnableEventSubscription: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "Enables event subscription to Notification List"
    Type: String
  CustomDBSecurityGroup:
    Description: The security group to apply to the database
    Type: AWS::EC2::SecurityGroup::Id
  Subnet1ID:
    Description: An existing subnet 1 
    Type: AWS::EC2::Subnet::Id
  Subnet2ID:
    Description: An existing subnet 2
    Type: AWS::EC2::Subnet::Id
  DBEngineVersion:
    Description: Select Database Engine Version
    Type: String
    Default: 9.6.12
    AllowedValues:
      - 9.6.1
      - 9.6.6
      - 9.6.9
      - 9.6.12
      - 9.6.14
      - 10.2
      - 10.5
      - 10.6
      - 10.7
      - 10.9
      - 11.1
      - 11.2
      - 11.4
Conditions:
  DBProvisionedIops:
    !Equals [!Ref DBStorageType, io1]
  UseDatabaseEncryption:
    !Equals [!Ref DBAllocatedStorageEncrypted, true]
  EventSubscription:
    !Equals
    - !Ref EnableEventSubscription
    - 'true'

Resources:
  DBSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref NotificationList
        Protocol: email
  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "Subnets available for the Postgres database instance"
      SubnetIds: 
       - !Ref Subnet1ID
       - !Ref Subnet2ID
  EncryptionKey:
    Condition: UseDatabaseEncryption
    DeletionPolicy: Retain
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub ["${RootStack}-key", RootStack: !Select [0, !Split ['-', !Ref 'AWS::StackName']]]
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: 'kms:*'
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ["${StackName} Encryption Key", StackName: !Ref 'AWS::StackName']
  EncryptionKeyAlias:
    Condition: UseDatabaseEncryption
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}"
      TargetKeyId: !Ref EncryptionKey
  DB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      DBInstanceClass: !Ref DBInstanceClass
      # In the next line of code the '-DB' delimeter is used to get the root stack name for database identifier
      # 'AWS::StackName' produces MASTER_STACK_NAME-DB (as DB is the name of the nested stack resource).
      DBInstanceIdentifier: !Sub ["${RootStack}-db", RootStack: !Select [0, !Split ['-', !Ref 'AWS::StackName']]]
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: postgres
      Port: !Ref DBPort
      DBName: !Ref DBName
      EngineVersion: !Ref DBEngineVersion
      Iops: !If [DBProvisionedIops, !Ref DBIops, !Ref 'AWS::NoValue']
      KmsKeyId: !If [UseDatabaseEncryption, !GetAtt EncryptionKey.Arn, !Ref 'AWS::NoValue']
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      MultiAZ: !Ref DBMultiAZ
      StorageEncrypted: !If [UseDatabaseEncryption, !Ref DBAllocatedStorageEncrypted, !Ref 'AWS::NoValue']
      StorageType: !If [DBProvisionedIops, io1, gp2]
      Tags:
        - Key: Name
          Value: !Sub ["${StackName} Confluence PostgreSQL Database", StackName: !Ref 'AWS::StackName']
      VPCSecurityGroups: [!Ref CustomDBSecurityGroup]
  DatabaseCPUUtilizationTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - Ref: DBSNSTopic
      AlarmDescription: 'Average database CPU utilization over last 10 minutes too high.'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DB
      EvaluationPeriods: 3
      MetricName: CPUUtilization
      Namespace: 'AWS/RDS'
      OKActions:
      - Ref: DBSNSTopic
      Period: 300
      Statistic: Average
      Threshold: 80
  DatabaseStorageSpaceTooLowAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - Ref: DBSNSTopic
      AlarmDescription: 'Average database free storage space over last 10 minutes too low.'
      ComparisonOperator: LessThanThreshold
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DB
      EvaluationPeriods: 3
      MetricName: FreeStorageSpace
      Namespace: 'AWS/RDS'
      OKActions:
      - Ref: DBSNSTopic
      Period: 300
      Statistic: Average
      Threshold: 5368709120 # 5 Gigabyte in Byte
      TreatMissingData: 'notBreaching'
  DatabaseEventSubscription:
    Condition: EventSubscription
    Type: 'AWS::RDS::EventSubscription'
    Properties:
      EventCategories:
      - availability
      - configuration change
      - deletion
      - failover
      - failure
      - maintenance
      - notification
      - recovery
      SnsTopicArn: !Ref DBSNSTopic
      SourceIds: [!Ref DB]
      SourceType: 'db-instance'
  DatabaseMaxUsedTxIDsAlarm1:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Ref: DBSNSTopic
      AlarmDescription: 'Maximum Used Transaction IDs'
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DB
      MetricName: 'MaximumUsedTransactionIDs'
      Statistic: Average
      Namespace: 'AWS/RDS'
      Threshold: 600000000
      Unit: Count
      ComparisonOperator: 'GreaterThanOrEqualToThreshold'
      Period: 60
      EvaluationPeriods: 5
      TreatMissingData: 'notBreaching'
Outputs:
  RDSEndPointAddress:
    Description: The Database Connection String
    Value: !GetAtt DB.Endpoint.Address
  RDSEndPointPort:
    Description: The port the DB endpoint listens on
    Value: !GetAtt DB.Endpoint.Port
  RDSEncryptionKey:
    Condition: UseDatabaseEncryption
    Description: The alias of the encryption key created for RDS
    Value: !Ref EncryptionKeyAlias